---
abstract: 'interface to the GitHub Jobs API.'
author:
  - 'Ovidiu Nita Tatar <ovn.tatar@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GitHub-Jobs
provides:
  GitHub::Jobs:
    file: lib/GitHub/Jobs.pm
    version: 0.05
requires:
  HTTP::Request: 6
  JSON: 2.57
  LWP::UserAgent: 6.05
  Moose: 2.0802
  Moose::Util::TypeConstraints: 2.0802
  MooseX::Params::Validate: 0.18
  Readonly: 1.03
  namespace::clean: 0.24
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
